#! /bin/sh

echo $RICE_DIR > ~/test

# for the key-binding daemon (we'll see it below)
sxhkd -c $RICE_DIR/sxhkdrc &

# for adding multiple monitors and workspaces
i=1
for monitor in $(bspc query -M); do
bspc monitor $monitor \
        -n "$i" \
        -d I II III IV V VI VII VII
    let i++
done

bspc config border_width         2

# I like to keep it 10, let me know what you think.
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
